esphome:
  name: aquasonic

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:
  # level: WARN

# Enable Home Assistant API
api:
  password: ""
  on_client_connected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));' 
        then:
          - light.turn_on: 
              id: wifi_led
              effect: blink_fast
          
  on_client_disconnected:
    - if:
        condition:
          lambda: 'return (0 == client_info.find("Home Assistant "));' 
        then:
          - light.turn_off: wifi_led
ota:
  - platform: esphome
    password: ""

wifi:
  networks:
  - ssid: !secret ssid1
    password: !secret password1
  enable_on_boot: True
  id: wlan
  on_connect: 
    then: 
      - light.turn_on:
          id: wifi_led
          effect: blink_slow

  on_disconnect: 
    then: 
      light.turn_off: wifi_led

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:

one_wire:
  - platform: gpio
    pin:
      number: 4
      mode:
        input: true
        pullup: true

sensor:
  - platform: dallas_temp
    address: 0xa53c9004572ebb28
    name: 'Water Temperature'
    update_interval: 60s
  - platform: dallas_temp
    address: 0x803c4ae381ded628
    name: 'Air Temperature'
    update_interval: 60s
  - platform: pulse_counter
    pin: GPIO18
    name: "Flow Pump 1"
  - platform: pulse_counter
    pin: GPIO19
    name: "Flow Pump 2"
  - platform: adc
    pin: GPIO32
    name: "Air Pressure 1"
    update_interval: 60s
  - platform: adc
    pin: GPIO33
    name: "Air Pressure 2"
    update_interval: 60s

output:
  - platform: gpio
    pin: LED
    id: led_wifi
light:
  - platform: binary
    id: wifi_led
    output: led_wifi
    effects:
      - strobe:
          name: "blink_slow"
          colors:
            - state: true
              duration: 100ms
            - state: false
              duration: 1900ms
      - strobe:
          name: "blink_fast"
          colors:
            - state: true
              duration: 200ms
            - state: false
              duration: 200ms
